version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    dns:
      - 8.8.8.8
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-with-nginx

  nodejs-app:
    build:
      context: ./node
    container_name: nodejsserver
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    hostname: nodejsserver
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3005:3005"
    dns:
      - 8.8.8.8
    depends_on:
      - db
    networks:
      - node-with-nginx

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "8080:80" 
    depends_on:
      - nodejs-app
    networks:
      - node-with-nginx

networks:
  node-with-nginx:
    driver: bridge